name: Lint
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'
          cache: false
      - 
        name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          only-new-issues: true  # Only show new issues for pull requests.
          args: --timeout=5m
