name: Lint
on:
  push:
    paths-ignore:
      - '**/*.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'
          cache: false
      - 
        name: Run tests
        run: go test -v ./...
